[FileDialog]
history=file:///home/dmxs/Downloads
lastVisited=file:///home/dmxs/Downloads
qtVersion=5.15.19
shortcuts=file:///, file:///home/dmxs, file:///home/dmxs/Documents, file:///home/dmxs/Downloads, file:///home/dmxs/Pictures, file:///home/dmxs/Desktop
sidebarWidth=70
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
