// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "2fe9b6e7-9e69-4c85-9444-d4e4d7f5664d");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1785515213);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1785720122);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "dda583ad-5f79-4d7a-989a-0033ee241705");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1785515211);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.ipProtection.added", true);
user_pref("browser.ipProtection.enabled", true);
user_pref("browser.ipProtection.stateCache", "unauthenticated");
user_pref("browser.ipProtection.usageCache", "");
user_pref("browser.migration.version", 175);
user_pref("browser.newtabpage.activity-stream.discoverystream.locale-weather-config", "en-CA, en-GB, en-US, pt-BR, es-AR, es-CL, es-MX");
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs", "newtab_stories_1, newtab_stories_2, newtab_stories_3, newtab_stories_4, newtab_stories_5, newtab_stories_6, newtab_stories_7, newtab_stories_8, newtab_stories_9, newtab_stories_10, newtab_stories_11, newtab_stories_12");
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs.counts", "1,1,1,1,1,1,1,1,1,1,1,1");
user_pref("browser.newtabpage.activity-stream.discoverystream.region-weather-config", "BR, AR, CL, CO, EC, MX, AU, NZ, ZA");
user_pref("browser.newtabpage.activity-stream.impressionId", "{54258261-ad26-4b62-bcf5-6baf3df52c32}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.pollLiveMs", 60000);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "154.8.20260716.43450");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1785515211);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1785720122004");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1785741722004");
user_pref("browser.search.region", "CL");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260729022412");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.lastColdStartupCheck", 1785720122);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1785720122);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"ipprotection-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ipprotection-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1785515);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b6ce08b7-9e69-49cf-a6b8-f9f6a918f22e");
user_pref("datareporting.dau.cachedUsageProfileID", "36549cde-30d8-4a7c-b3d8-b2dffd678584");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1785515212848");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "153.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CL");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "e3e7e50ebed345069a7f91d70895e3d4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260729022412");
user_pref("extensions.lastAppVersion", "153.0.1");
user_pref("extensions.lastPlatformVersion", "153.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ef9aa7d5-bd4a-4963-9e36-8e55582cb375\",\"ipp-activator@mozilla.com\":\"148afc8e-b809-4c51-9e04-be8a8535548f\",\"pictureinpicture@mozilla.org\":\"08e23ae9-f965-4030-8cba-3dd7607df44f\",\"addons-search-detection@mozilla.com\":\"7245d590-3d5c-4030-95a9-918b761b8bc1\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"f6ae89bc-950b-40fd-b77e-cd1825240369\",\"default-theme@mozilla.org\":\"ccbebcb1-ba0b-449a-9462-d0ddd561004f\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 4);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "aa3ecbda-4e50-4526-a941-49f90de9b5d1");
user_pref("nimbus.syncdefaultsstore.pocketNewtab", "{\"slug\":\"hnt-weather-with-location-selector-non-eu-expansion-romance-and-germanic-lang\",\"source\":\"rs-loader\",\"userFacingName\":\"HNT weather with location selector non-EU expansion Romance and Germanic Lang\",\"userFacingDescription\":\"Providing weather widget on the newtab to more countries\",\"lastSeen\":\"2026-07-31T16:26:51.972Z\",\"featureIds\":[\"pocketNewtab\"],\"isRollout\":true,\"prefs\":[{\"name\":\"browser.newtabpage.activity-stream.discoverystream.locale-weather-config\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"localeWeatherConfig\",\"originalValue\":null},{\"name\":\"browser.newtabpage.activity-stream.discoverystream.region-weather-config\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"regionWeatherConfig\",\"originalValue\":null},{\"name\":\"browser.newtabpage.activity-stream.weather.locationSearchEnabled\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"weatherLocationSearch\",\"originalValue\":null}],\"active\":true,\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"pocketNewtab\"},\"features\":null,\"firefoxLabsTitle\":null},\"localizations\":null,\"isFirefoxLabsOptIn\":false,\"firefoxLabsTitle\":null,\"firefoxLabsDescription\":null,\"firefoxLabsDescriptionLinks\":null,\"firefoxLabsGroup\":null,\"requiresRestart\":false}");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.localeWeatherConfig", "en-CA, en-GB, en-US, pt-BR, es-AR, es-CL, es-MX");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.regionWeatherConfig", "BR, AR, CL, CO, EC, MX, AU, NZ, ZA");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.weatherLocationSearch", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.settings.server", "https://firefox.settings.services.mozilla.com/v2");
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "6e994c15");
user_pref("toolkit.startup.last_success", 1785720119);
user_pref("toolkit.telemetry.cachedClientID", "4b148e8f-9106-471b-ad98-66a04cbfa971");
user_pref("toolkit.telemetry.cachedProfileGroupID", "b90bba1f-8992-46ff-a36d-d7bbae023269");
user_pref("toolkit.telemetry.previousBuildID", "20260729022412");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
